### ISSUE TITLE
scaffold the layer control pane

### ISSUE THREAD

**Issue by thatbudakguy** [watzek/cdo#12]
find some fun bootstrap components

 https://getbootstrap.com/docs/4.0/examples/offcanvas/ ?

**Comment by thatbudakguy** [comment]
http://reactstrap.github.io/components/alerts/

**Comment by owen-will-m** [comment]
The Media  that we were looking at doesn't seem to have very good onClick functionality. The onClick that I give it will activate upon loading, and then not again. Additionally, if I put a Button  inside that media, it only activates its onClick once. 

I suggest we find a better component than Media, or perhaps reconsider the previously suggested scaffold. 
I think Media  wasn't designed to be clicked.
